SRC_URL = 'https://nationaladdressdata.s3.amazonaws.com/NAD_r9_TXT.zip'
#SRC_URL = 'https://nationaladdressdata.s3.amazonaws.com/NAD_r9.zip'
PATH = 'TXT/NAD_r9.txt'
TEMPORARY_DIRECTORY = '/mnt/hdd/benjamin/tmp'
INDEX_LONG = 30
INDEX_LAT = 31
MAX_FEATURES = -1 #20000000
TILE_MINZOOM = 0
TILE_MAXZOOM = 14
